version: 2

jobs:
  build:
    docker:
      - image: maukoquiroga/transport:0.0.1
        environment:
          MIX_ENV: test
          DATAGOUVFR_SITE: https://www.data.gouv.fr

    steps:
      - checkout

      - restore_cache:
          keys:
            - elixir-{{ checksum "mix.lock" }}

      - restore_cache:
          keys:
            - node-{{ checksum "client/yarn.lock" }}

      - run:
          name: Install dependencies
          command: |
            mix deps.get
            mix yarn install

      - run:
          name: Run compile
          command: |
            mix deps.compile
            mix compile
            cd client && npm run build

      - save_cache:
          key: elixir-{{ checksum "mix.lock" }}
          paths:
            - _build
            - deps
            - ~/.mix

      - save_cache:
          key: node-{{ checksum "client/yarn.lock" }}
          paths:
            - client/node_modules

      - run:
          name: Start webdriver
          command: /etc/init.d/phantomjs start

      - run:
          name: Run tests
          command: |
            export SECRET_KEY_BASE=`mix phx.gen.secret`
            mix test
            mix test --only integration

      - run:
          name: Run linters
          command: |
            mix credo --strict
            eslint -c .eslintrc client
            sass-lint -c .sass-lint.yml  -v -q

      - run:
          name: Setup Heroku
          command: |
            git remote add heroku https://git.heroku.com/transport-beta.git

            cat > ~/.netrc << EOF
            machine api.heroku.com
              login $HEROKU_LOGIN
              password $HEROKU_API_KEY
            machine git.heroku.com
              login $HEROKU_LOGIN
              password $HEROKU_API_KEY
            EOF

            ssh-keyscan -H heroku.com >> ~/.ssh/known_hosts

      - add_ssh_keys:
          fingerprints:
            - "ec:1c:68:6e:d7:46:29:87:af:67:46:a2:ea:a5:8e:fb"

      - deploy:
          name: Deploy master to Heroku
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              git push heroku master
              heroku restart
            fi

